In [1]:
import torch

In [34]:
t = torch.rand((2, 3, 5, 5))
print(t)

drop = torch.nn.Dropout2d(p=0.5)

t = drop(t)
print(t)

tensor([[[[0.2582, 0.7063, 0.8768, 0.2676, 0.0939],
          [0.8009, 0.4016, 0.4805, 0.3646, 0.2659],
          [0.4820, 0.6136, 0.3926, 0.1232, 0.4298],
          [0.9690, 0.7328, 0.9374, 0.8633, 0.6269],
          [0.9917, 0.1240, 0.2655, 0.8295, 0.5889]],

         [[0.5306, 0.7439, 0.2477, 0.4193, 0.3922],
          [0.0755, 0.3598, 0.5540, 0.0581, 0.4579],
          [0.5568, 0.7944, 0.9675, 0.4172, 0.0071],
          [0.8556, 0.2279, 0.3881, 0.8817, 0.8780],
          [0.3625, 0.8152, 0.0776, 0.1023, 0.4420]],

         [[0.3068, 0.6987, 0.0855, 0.2618, 0.4842],
          [0.2500, 0.9718, 0.8271, 0.6320, 0.9124],
          [0.6532, 0.8029, 0.8121, 0.3210, 0.3358],
          [0.0130, 0.6454, 0.2163, 0.8277, 0.1189],
          [0.9764, 0.5271, 0.0663, 0.7408, 0.9972]]],


        [[[0.0538, 0.8195, 0.5905, 0.6595, 0.8117],
          [0.6356, 0.6374, 0.7504, 0.5926, 0.5543],
          [0.2822, 0.2317, 0.1024, 0.5242, 0.5013],
          [0.0627, 0.5329, 0.3751, 0.8400, 0.0122],
    

In [58]:
generator = torch.Generator()
generator.manual_seed(1)
print(torch.bernoulli(torch.ones((3, 3)) * 0.5, generator=generator))
print(torch.bernoulli(torch.ones((3, 3)) * 0.5, generator=generator))

generator.manual_seed(1)
print(torch.bernoulli(torch.ones((3, 3)) * 0.5, generator=generator))
print(torch.bernoulli(torch.ones((3, 3)) * 0.5, generator=generator))

tensor([[0., 1., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 1.],
        [1., 0., 1.]])
tensor([[0., 1., 1.],
        [0., 1., 0.],
        [1., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 1.],
        [1., 0., 1.]])
